export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
}

export enum TripStatus {
  DRAFT = 'DRAFT',
  UPCOMING = 'UPCOMING',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ActivityCategory {
  PHYSICAL_ACTIVITY = 'PHYSICAL_ACTIVITY',
  SIGHTSEEING = 'SIGHTSEEING',
  CULTURAL = 'CULTURAL',
  ADVENTURE = 'ADVENTURE',
  FOOD_AND_DINING = 'FOOD_AND_DINING',
  ENTERTAINMENT = 'ENTERTAINMENT',
  SHOPPING = 'SHOPPING',
  RELAXATION = 'RELAXATION',
  OTHER = 'OTHER',
}
